### ISSUE TITLE
Run first large scale vision experiment with moving Retina

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/walnut#107]
Plan for experiment here:
https://docs.google.com/a/vt.edu/document/d/1lu7fnAmLFZyRgpgRXtxdk-o3Z2WP_X5sf2t6-CTbJ4Y/edit?usp=sharing

**Comment by quinnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/2585159/6609326/5bf96c6e-c826-11e4-9073-cfdcc4a4fec9.png)

**Comment by quinnliu** [comment]
TODO: When overlap X & Y are set correctly we are getting the following error: 
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at model.MARK_II.connectTypes.RegionToRegionRectangleConnect.connect(RegionToRegionRectangleConnect.java:41)
	at model.MARK_II.Neocortex.addToCurrentRegion(Neocortex.java:118)
```

**Comment by quinnliu** [comment]
TODO: Consider creating a generic traversal strategy across the neocortex that creates each region and then saves it. While running the SP & TP algorithm open a region, run SP & TP on it and then save it. Then do this for all regions in the necortex...

**Comment by quinnliu** [comment]
<b>Next Action:</b> 1) Recalculate stats for experiment as I did it very wrong
2) Write important details up in MARK_II readme.md for Experiment_1.java

**Comment by quinnliu** [comment]
<b>1st Next Action:</b> Run the original experiment outlined in e-mail to nupic-theory@lists.numenta.org 

Hi,
   My name is Quinn. I am trying to build a vision experiment using HTM and I wanted to get some feedback to make sure that I am not missing anything or got anything wrong.
 
This image here: https://db.tt/StwocQ9q (you will need to zoom out) 
represents the experiment I want to run. I've already written most of the code to build this model here: https://github.com/WalnutiQ/WalnutiQ

If you feel that anything below doesn't make sense please let me know why. Also I would love to hear any suggestions. Thanks!

Please refer to the image while reading below:
@ t = 0, the Retina is looking initially at the entire image. Then the Layer 4 Regions processing the Retina input using SP. The active columns produced by SP are passed on as input to the Layer 3 Regions processing the input with SP & TP. This is done again to a smaller Layer 3 & 4. You can also see that Layer 5 is represented with a Region that is used to determine where the Retina is moved(saccaded) to next. In the image, the active neurons within the Layer 5 Region makes the Retina zoom in on the image and shift a little to the left producing the seen image @ t = 1.

Additionally I am making all columns in Layer 4 with 1 neuron & columns in Layer 3 with 4 neurons.

So my idea for an experiment is to run the learning algorithm over & over until t = 1 million times.

The input images would be 10 images(from different perspectives) of the same persons face.

Then I would record the activity of neurons statistics(which ones were active & predictive) in the highest Layer 3 Regions for the last 100 timesteps where the Retina was ONLY looking at the entire face to basically use for face object recognition later. So for example if the retina saccades to just the eyes of the person at t = 1 million - 1 I would not include the statistics of the neurons in the highest Layer 3 Regions.

I would then repeat the above training strategy with something else like a tree for example.

Then as a very simple test I changed the input image to something the model has never seen and let the learning algorithm run for 100 time steps & record the neuron activity of the highest Layer 3 Region. I could then compare it to the face & the tree and do this for object recognition. 

I would love to hear what you think.

Thanks,
Quinn Liu

quinnliu@vt.edu

**Comment by quinnliu** [comment]
<b>0th Next Action:</b>
```java
ImageViewer imageViewer = new ImageViewer("imageOfHumanFace1000x1000pixels.bmp",
                bigNervousSystem.getBigRetina().getSavedRetinaFromDisk());
```

**Comment by quinnliu** [comment]
Focusing on 1 thing for now.
